---
    - hosts: Master
      vars:
        apim_component_name: ps
      become: 'yes'
      tasks:
        - name: Install k8s
          command: "sudo kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=all"
          become: yes
          register: k8_output
        - debug:
            var: k8_output.stdout_lines[-2],k8_output.stdout_lines[-1] 
            
        #- local_action: lineinfile line={{ k8_output.stdout_lines[-2],k8_output.stdout_lines[-1] }} path=/devops_demo1/Master-Node/ansible/output
---
    - hosts: Master
      become: yes
      gather_facts: false
      tasks:
          - name: get join command
            shell: kubeadm token create --print-join-command
            register: join_command_raw

          - name: set join command
            set_fact:
              join_command: "{{ join_command_raw.stdout_lines[0] }}"
---
    - hosts: Workers
      become: yes
      tasks:
         - name: join cluster
           shell: "{{ hostvars['Master'].join_command }} >> node_joined.txt"
           args:
             chdir: $HOME
             creates: node_joined.txt